# Name of the project
PROJECT_NAME = Contact_management_system

#Doxyfile folder
DOC = documentation

#All source code files
SRC = contactmanagementsystem.c\
src/contactmanagementsystem_operations.c

#All test source files
TEST_SRC = src/contact_operations.c\
test/test_contact_operations.c\
unity/unity.c

TEST_OUTPUT = Test_a.out

#All include folders with header files
INC = -Iinc\
-Iunity\

#Project Output Name
PROJECT_OUTPUT = contactmanagementsystem.exe

#Document files
DOCUMENTATION_OUTPUT = documentation/html


Build:
	gcc function1.c test_contactmanagementsystem.c unity/unity.c -Iunity

Run:
	./a.out